# Generated by Django 5.0.7 on 2024-07-12 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(default='A', max_length=100),
            preserve_default=False,
        ),
    ]
