# Generated by Django 5.0.7 on 2024-07-16 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cartorderitems_invoice_no'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name_plural': 'Tags'},
        ),
    ]
