# Generated by Django 5.0.7 on 2024-07-17 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_product_life_product_mfd_product_stock_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='authentic_rating',
            field=models.CharField(default='80', max_length=100),
        ),
    ]
