# Generated by Django 5.0.7 on 2024-07-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_vendor_authentic_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='authentic_rating',
            field=models.CharField(default='100', max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='warranty_period',
            field=models.CharField(default='12', max_length=100),
        ),
    ]
