# Generated by Django 5.0.7 on 2024-07-17 21:29

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default="Introducing the [Product Name], the ultimate blend of innovation and style. Designed to cater to your dynamic lifestyle, this product stands out with its state-of-the-art features and sleek design. Whether you're at home, work, or on the go, the [Product Name] ensures seamless performance and unparalleled convenience. Explore a world of possibilities with this top-tier product that combines cutting-edge technology with user-friendly functionality. Experience the perfect harmony of efficiency and elegance, crafted to meet your every need and exceed your expectations.", null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='specification',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='- **Display**: 6.5-inch Full HD+ OLED, 1080 x 2400 pixels\n- **Processor**: Octa-core, 2.84 GHz\n- **RAM**: 8GB\n- **Storage**: 128GB internal, expandable up to 1TB via microSD\n- **Camera**: Triple rear cameras (64MP + 12MP + 5MP), 32MP front camera\n- **Battery**: 4500mAh, fast charging support\n- **Operating System**: Android 11, upgradable to Android 12\n- **Connectivity**: 5G, Wi-Fi 6, Bluetooth 5.1, NFC\n- **Ports**: USB Type-C, 3.5mm headphone jack\n- **Dimensions**: 160.8 x 78.1 x 7.4 mm\n- **Weight**: 190g\n- **Additional Features**: In-display fingerprint sensor, face recognition, IP68 water and dust resistance', null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(default="Welcome to [Vendor Name]! We are passionate about delivering high-quality products and exceptional customer service. Our extensive collection includes everything from the latest trends to timeless classics, ensuring that you find exactly what you're looking for. At [Vendor Name], we believe in the power of choice and strive to offer a diverse range of products to suit every need and preference. Whether you're shopping for yourself or looking for the perfect gift, our dedicated team is here to make your experience seamless and enjoyable. Explore our store today and discover why [Vendor Name] is your go-to destination for quality and value."),
        ),
    ]
